spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  flyway:
    enabled: true
    user: ${DB_FLYWAY_USER}
    password: ${DB_FLYWAY_PASSWORD}
    default-schema: ${DB_SCHEMA}
    schemas: ${DB_SCHEMA}
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default-schema: ${DB_SCHEMA}

  application:
    name: service
