#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<-SQL
    CREATE SCHEMA IF NOT EXISTS ${DB_SCHEMA} AUTHORIZATION ${DB_FLYWAY_USER};

    GRANT USAGE ON SCHEMA ${DB_SCHEMA} TO ${DB_USER};

    ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_FLYWAY_USER} IN SCHEMA ${DB_SCHEMA}
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_USER};

    ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_FLYWAY_USER} IN SCHEMA ${DB_SCHEMA}
    GRANT USAGE, SELECT ON SEQUENCES TO ${DB_USER};
SQL